### PR TITLE
Atualização das instruções de instalação para Mac OSX Mountain Lion

### PR DESCRIPTION
**Pull request by lucascaton**

### CODE REVIEW

**Comment by danielvlopes** [comment]
Fala Lucas, blz? 

So, my goal with this repo/wiki is to help the newcomers with a step by step guide of the easiest way to install Ruby and everything required to start. I'm not sure if install an old version of Ruby is the kind of thing that is important for beginners, probably is for intermediates but they can research for themselves.

**Comment by lucascaton** [comment]
Makes sense! :-)

**Comment by danielvlopes** [comment]
Anyway, thanks for the help.

**Comment by lucascaton** [comment]
:-)

**Pull request closed without merging**
